application: guestbook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# access the static resources in the root director

- url: /(.*)
  static_files: \1
  upload: (.*)


- url: .*
  script: guestbook.app



libraries:
- name: webapp2
  version: "2.5.2"
